import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "@/app/providers";
import "./globals.css";

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
	weight: "300",
});

export const metadata: Metadata = {
	title: "🔗 Link My Image 🔗",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html className={`${inter.variable}`}>
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
